#
# look-brownsteel.conf
#
# Based on look-jarkko.conf by Jarkko Sakkinen (sakkinen@students.cc.tut.fi)
#

font "-*-helvetica-bold-r-normal-*-12-*-*-*-*-*-*-*"
menu_font "-*-helvetica-medium-r-normal-*-12-*-*-*-*-*-*-*"

# border width, bevel width
border_w 1, 0

# bar min width, bar max width q, tab min width
bar_w 150, 0.95, 50

# 			highlight, shadow, background, foreground
act_tab_colors		"#803020", "#401000", "#502010", "#a0a0a0"
act_tab_sel_colors	"#203080", "#001040", "#102060", "#ffffff"
act_base_colors		"#202060", "#101030", "#181850", "#a0a0a0"
act_sel_colors		"#3030a0", "#202040", "#202080", "#a0a0a0"

tab_colors		"#201810", "#100800", "#181008", "#707070"
tab_sel_colors		"#401810", "#200800", "#281008", "#808080"
base_colors		"#402020", "#201010", "#301818", "#a0a0a0"
sel_colors		"#707070", "#404040", "#505050", "#a0a0a0"
